[package]
name = "todo-leptos"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
leptos = { version = "0.5.4", features = ["csr", "nightly"] }
uuid = { version = "1.6.1", features = ["v4"] }
instant = { version = "0.1.12", features = [ "wasm-bindgen", "inaccurate" ] }