[package]
name = "todo-leptos"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
leptos = { version = "0.5.2", features = ["csr", "nightly"] }
uuid = { version = "1.5.0", features = ["v4"] }
instant = { version = "0.1", features = [ "wasm-bindgen", "inaccurate" ] }